### ISSUE TITLE
Documentation - Spatial Join example

### ISSUE THREAD

**Issue by jnidzwetzki** [StonyBrookDB/hadoopgis#3]
Hello,

The [documentation](http://bmidb.cs.stonybrook.edu/hadoopgis/examples) provides some examples for Hadoop-GIS. However, the example 'Spatial Join Execution' seems to contain some errors.

I was unable to execute the spatial join from the documentation in my environment. The documentation contains the following program call:

```
./build/bin/queryprocessor_2d -b YOUR_HDFS_PATH/zipcode -a YOUR_HDFS_PATH/tweets/ -p st_within --outputpath YOUR_HDFS_PATH/spatialjoinout--numreducers 20 --outputfields 1:1,1:2,1:3,1:4,1:5,2:3 --partitioner bsp
```

It seems, there are some mistakes in the example:

* The parameter '-p st_within' does not stand for the predicate. I assume '--predicate st_within' is the proper argument
* The parameter '-q spjoin' seems to be mandatory for executing a spatial join
* There is a space missing between 'spatialjoinout' and '--numreducers'
* The full path to the input files ('-a' and '-b') seems to be required
* The input files contain the geometry in the second field, therefore '-i 2 -j 2' should be added
* The partitioner 'bsp' is unknown. I assume 'bsp_2d' meant here

In my opinion, the call should be look like this:

```
./build/bin/queryprocessor_2d -b YOUR_HDFS_PATH/zipcode/rawdata/zcta510.tsv -a YOUR_HDFS_PATH/tweets/rawdata/tweets.filtered.tsv --outputpath YOUR_HDFS_PATH/spatialjoinout --numreducers 20 --outputfields 1:1,1:2,1:3,1:4,1:5,2:3 --partitioner bsp_2d --predicate st_within -q spjoin -i 2 -j 2
```

Could anybody have a look at this issue and check if my version is correct?

Thank you very much in advance.

Best Regards
    Jan

**Comment by voviethoang** [comment]
Thank you!
The issue has been fixed. We have added adjustments and changes to account for our HadoopGIS 3D/iSPEED project that created unnecessary issues and bugs.

Thank you again!

Warmest regards,
Hoang
